network_tiers:
  security_groups:
    - name: web
    - name: application
    - name: database
    - name: management
  cidr_blocks:
    - name: incoming_https
    - name: outgoing_https
    - name: incoming_management_ssh

traffic_rules:
  - source: incoming_https
    destination: web
    traffic_type: https

  - source: web
    destination: application
    traffic_type: https

  - source: application
    destination: database
    traffic_type: postgresql

  - source: incoming_management_ssh
    destination: management
    traffic_type: ssh

  - source: management
    destination: all_security_groups

